name: tile_server
description: Miniature tile server designed to test FMTC's throughput and download speeds.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console: ^1.2.0
  jaguar: ^3.1.3
  path: ^1.9.0
